// MOVIES ACTION TYPES
export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES'
export const SAVE_MOVIE = 'SAVE_MOVIE'
export const DELETE_MOVIE_FROM_SAVED_LIST = 'DELETE_MOVIE_FROM_SAVED_LIST'
export const DELETE_ALL_MOVIES_FROM_SAVED_LIST =
  'DELETE_ALL_MOVIES_FROM_SAVED_LIST'
export const SET_ERRORS = 'SET_ERRORS'
export const REGISTER_USER = 'REGISTER_USER'
