// MOVIES ACTION TYPES
export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES'
export const SAVE_MOVIE = 'SAVE_MOVIE'
export const DELETE_MOVIE_FROM_SAVED_LIST = 'DELETE_MOVIE_FROM_SAVED_LIST'
export const DELETE_ALL_MOVIES_FROM_SAVED_LIST =
  'DELETE_ALL_MOVIES_FROM_SAVED_LIST'
export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
